LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),olympus)

include $(CLEAR_VARS)

LOCAL_SRC_FILES := hijack.c

LOCAL_MODULE := hijack
LOCAL_MODULE_TAGS := eng

LOCAL_STATIC_LIBRARIES := \
	libbusybox \
	libclearsilverregex \
	libm \
	libcutils \
	libc

LOCAL_FORCE_STATIC_EXECUTABLE := true

ifneq ($(BOARD_HIJACK_UPDATE_BINARY),)
LOCAL_CFLAGS += -DUPDATE_BINARY=\"$(BOARD_HIJACK_UPDATE_BINARY)\"
endif

ifneq ($(BOARD_HIJACK_RECOVERY_UPDATE_ZIP),)
LOCAL_CFLAGS += -DRECOVERY_UPDATE_ZIP=\"$(BOARD_HIJACK_RECOVERY_UPDATE_ZIP)\"
endif


ifneq ($(BOARD_HIJACK_RECOVERY_MODE_FILE),)
LOCAL_CFLAGS += -DRECOVERY_MODE_FILE=\"$(BOARD_HIJACK_RECOVERY_MODE_FILE)\"
endif

include $(BUILD_EXECUTABLE)


endif
